### ISSUE TITLE
ERROR found with 'EngineIdleRPM'

### ISSUE THREAD

**Issue by ltorrespr** [jeremySchriver/Forza_telemetry_project#9]
Thank you very much! Will grab code right now. BTW, will it give me a Warning/Error for any missing Libraries?

Seems the overall process changed, so, will do more work/analysis tomorrow. Before when I ran the telemetryCapture.py, it would automatically capture the data from my XBox, now it goes through various questions prior to the capture/analysis. I tested with Y (and yes/Yes/YES), then, N (no/No/NO) and at the end it gave me various errors. I think I first have to manually enter the car data and probably deleting the existing files you have already captured days back prior to then running the new car.

The only car saved I saw was within the Directory 3655, yet, it mentioned 2352 for some reason, which is not the car I have either.

Info received after the question, "Do you want to rename the file?"....
Note: New file name would already be named 2352_logTelemetry.csv and would be placed in its respective TelemDataFiles directory
Traceback (most recent call last):
File "/Documents/Forza-Telemetry/JeremyS/Forza_telemetry_project-main/telemetryCapture.py", line 90, in
df.to_csv(path, index=False)
File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3466, in to_csv
return DataFrameRenderer(formatter).to_csv(
File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
csv_formatter.save()
File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 237, in save
with get_handle(
File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 702, in get_handle
handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/Forza-Telemetry/JeremyS/Forza_telemetry_project-main/TelemDataFiles/2352/2352_logTelemetry.csv'
(base)

**Comment by jeremySchriver** [comment]
@ltorrespr I'm so sorry I'm not sure how this one slipped through the cracks and I didn't respond to your message. Are you still having issues running the application?

**Comment by ltorrespr** [comment]
Jeremy,

No worries! I was out for about 1 month with family activities/travelling.  The last time I used it, yes, I still had some issues.  However, I will download your latest build and test it out.  Thank you very much for all your work on this.

Regards,
Luis
________________________________
